### ISSUE TITLE
Broken tag v1.7.2

### ISSUE THREAD

**Issue by kpeder** [terraform-google-modules/terraform-google-cloud-storage#102]
The release tag points to this commit: https://github.com/terraform-google-modules/terraform-google-cloud-storage/commit/935f42c625c28468de8fb76003cf451e0cfc9915

...which doesn't exist on master, and returns the message: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

Also seeing this:

```
~/projects/terraform-google-cloud-storage$ git pull origin master 
From github.com:kpeder/terraform-google-cloud-storage
 * branch            master     -> FETCH_HEAD
Already up to date.
~/projects/terraform-google-cloud-storage$ git pull origin --tag
Already up to date.
~/projects/terraform-google-cloud-storage$ git checkout v1.7.2
Note: switching to 'v1.7.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 935f42c fix: Fix deprecation of is_live lifecycle rule (#91)
```

...I have been using the branch as a reference in the meantime.

**Comment by morgante** [comment]
Can you explain what is broken / how to reproduce?

The tag is here: https://github.com/terraform-google-modules/terraform-google-cloud-storage/tree/v1.7.2

**Comment by kpeder** [comment]
Just offhand, I would say that the patch/v1.7.2 branch was force-pushed over top of the commit that the original tag was pointing to, and the tag is still applied to the overwritten commit, instead of the new one:

Commit hash from master (after force-push):
```
commit f73041b904d8f5c7020efb84737d54869e394738
Author: Brent Heinz <heiny@users.noreply.github.com>
Date:   Mon Sep 28 15:05:25 2020 -0700

    fix: Fix deprecation of is_live lifecycle rule (#91)
```

Commit hash from tag v1.7.2 (original commit; no longer exists on master branch):
```
commit 935f42c625c28468de8fb76003cf451e0cfc9915 (HEAD, tag: v1.7.2)
Author: Brent Heinz <heiny@users.noreply.github.com>
Date:   Mon Sep 28 15:05:25 2020 -0700

    fix: Fix deprecation of is_live lifecycle rule (#91)
```

**Comment by morgante** [comment]
Ok, but can you explain more about how to reproduce? I'm seeing the tag still exists.

**Comment by kpeder** [comment]
> Ok, but can you explain more about how to reproduce? I'm seeing the tag still exists.

It does certainly exist. This issue is only that it points to a commit in the repository's history, not in the actual master branch. This commit that the tag points to generates a headless state. This isn't functionally an issue, except that if your automation were to exit on error:

error: pathspec 'v1.7.2' did not match any file(s) known to git

Then your deployment workflow tends to exit.

**Comment by morgante** [comment]
Since the tag exists and I'm not seeing how this introduces any functional errors/issues, I'm going to close.

If this *is* having a functional impact I'm not seeing feel free to reopen.

**Comment by kpeder** [comment]
> Since the tag exists and I'm not seeing how this introduces any functional errors/issues, I'm going to close.
> 
> If this _is_ having a functional impact I'm not seeing feel free to reopen.

Seriously? My deployment pipeline exits with an error. Cloning this tag generates an error in git, because the commit doesn't exist in the tree. Don't you want a valid tag?

**Comment by morgante** [comment]
I'm not fully sure I understand how your deployment pipeline is broken/failing. I didn't meant to break your workflow, I meant that none of our automation or typical automation I'd expect should break.

Are you directly cloning the repo (ie. not using the Terraform module syntax)?

**Comment by kpeder** [comment]
I am directly cloning the repo, and via a terragrunt-driven invocation of the module, pinned to this tag and using ssh (by convention, because we also use private module repos... I have tests via HTTPS with the same result).

I thought it was a shallow clone issue, but in fact I think it's perhaps a go-git thing, something similar to this: https://github.com/src-d/go-git/issues/574#issuecomment-326933335.

In any event, it's the only broken tag I have, and the apparent difference is that it's not pointing to a commit that lives on any branch.

**Comment by morgante** [comment]
Ok, this still sounds like a bug in the tool you're using. I am able to check out the tag no problem.
