### ISSUE TITLE
Lifecycle rules applied to specific buckets

### ISSUE THREAD

**Issue by manalj** [terraform-google-modules/terraform-google-cloud-storage#110]
Currently the default behaviour for `lifecycle_rules` configuration is to be applied for every bucket, unlike the other configurations (e.g. `versioning`)

https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/main.tf#L92

Can we update the above to use a lookup so that the lifecycle rules are only applied for a specific set of buckets?

**Comment by manalj** [comment]
Keep open

**Comment by manalj** [comment]
keep open

**Comment by manalj** [comment]
keep

**Comment by Leoduv** [comment]
we would also be interested in this being possible
