### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by adinhodovic** [terraform-google-modules/terraform-google-cloud-storage#112]
Can you release a new version with https://github.com/terraform-google-modules/terraform-google-cloud-storage/commit/1fe315a8ab722d7f91b60e1c209bf938724eb371?

https://registry.terraform.io/modules/terraform-google-modules/cloud-storage/google/latest

**Comment by morgante** [comment]
Unfortunately we still need an [upgrade guide](https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/87#issuecomment-697551687).
