### ISSUE TITLE
days_since_custom_time - syntax reference 

### ISSUE THREAD

**Issue by mike-19** [terraform-google-modules/terraform-google-cloud-storage#118]
There appears to be a documentation error for the google provider  raised an issue for correction [1] 

by using an integer value for the lifecycle rule I am getting 400 Bad Request error, Can someone help here 

` lifecycle_rules = [{
action = {
  type = "Delete"
}
condition = {
  days_since_custom_time        = 10
}
 }]
}`

> Error: googleapi: Error 400: Invalid argument, invalid
{“error”:{“code”:400,“message”:“Invalid argument”,“errors”:[{“message”:“Invalid argument”,“domain”:“global”,“reason”:“invalid”}]}}:

**Comment by petomalina** [comment]
@mike-19 can you please re-open this issue? I just came across the same problem and it doesn't look to be solved in the module implementation. Thanks!

**Comment by petomalina** [comment]
@morgante I believe this issue can now be closed
