### ISSUE TITLE
Location included in the bucket name? 

### ISSUE THREAD

**Issue by nesth** [terraform-google-modules/terraform-google-cloud-storage#12]
Version 1.0.0 now includes the location in the bucket name. Version 0.1.0 did not. 

Have the location in the bucket name is good practice, but shouldn't 1.0.0 be backwards compatible?

**Comment by morgante** [comment]
Indeed this did change. Major version changes aren't guaranteed to be backwards-compatible (we follow semantic versioning, ie. v0.1.0 to v1.0.0 or v1.0.0 to v2.0.0).

If you need the ability to exclude location prefixes, we could add a variable?

**Comment by christopher-tin** [comment]
FYI, we bypassed this issue by not using the prefix anymore and put what we wanted in the name of the bucket.
