### ISSUE TITLE
The default value for storage_class variable in this module is using deprecated option "MULTI_REGIONAL"

### ISSUE THREAD

**Issue by LuizSDCit** [terraform-google-modules/terraform-google-cloud-storage#122]
The current default value for `storage_class` variable is [`"MULTI_REGIONAL"`](https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/variables.tf#L38):

```terraform
variable "storage_class" {
  description = "Bucket storage class."
  type        = string
  default     = "MULTI_REGIONAL"
}
```

This value is deprecated according to the [documentation of Cloud Storage](https://cloud.google.com/storage/docs/storage-classes#legacy)

> **Additional classes**
Cloud Storage supports several additional storage classes; however, these classes cannot be set using the Cloud Console. Unless you already are using one of these additional classes, you should use Standard Storage instead.

According to this, I suggest changing the default value to `"STANDARD"`.

**Comment by bharathkkb** [comment]
Thanks for the report @LuizSDCit  Happy to review a PR for this.

Some additional context https://github.com/hashicorp/terraform-provider-google/issues/4422

**Comment by morgante** [comment]
We should probably actually just use a `null` default.
