### ISSUE TITLE
Error in function call

### ISSUE THREAD

**Issue by AgustinNormand** [terraform-google-modules/terraform-google-cloud-storage#123]
Hi, 

Im trying to use this module and I'm getting this error:

```
│ Error: Error in function call
│ 
│   on .terraform/modules/gcs_buckets/main.tf line 18, in locals:
│   18:   prefix = var.prefix == "" ? "" : join("-", list(var.prefix, lower(var.location), ""))
│     ├────────────────
│     │ var.location is "EU"
│     │ var.prefix is "my-unique-prefix"
│ 
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax
│ to write a literal list.
```

Im doing the same thats in [this](https://registry.terraform.io/modules/terraform-google-modules/cloud-storage/google/latest) tutorial.

Is this a bug? Can you help me? 

Thanks!

**Comment by bharathkkb** [comment]
Hi @AgustinNormand 

We fixed this #107 so it should work with `version = "~> 2.0"`

**Comment by AgustinNormand** [comment]
Thanks! I didn't know I wasn't using the latest version. Sorry for asking.

**Comment by bharathkkb** [comment]
no worries at all, our readmes were out of date.
