### ISSUE TITLE
simple_bucket - no possibility to add multiple members to role in one statement

### ISSUE THREAD

**Issue by zolech** [terraform-google-modules/terraform-google-cloud-storage#133]
Hi,

It seems that I cannot add multiple members to a role. I tried these:
1)
`    {
        role   = "roles/storage.legacyBucketOwner"
        member = "projectEditor:${module.project-factory.project_id}, projectOwner:${module.project-factory.project_id}"
    }
`
2)
`
 {
role   = "roles/storage.legacyBucketOwner"
member = ["projectEditor:${module.project-factory.project_id}", "projectOwner:${module.project-factory.project_id}"]
 }
`

Do I have to specify this statement twice for the same role but with different member or am I missing something?

**Comment by morgante** [comment]
Yes, you have to specify each member separately.

**Comment by zolech** [comment]
Thank for the response @morgante . Can it be worked out to pass an array of members or there are some difficulties preventing this that I am not aware of? I could look into it if it makes any sense.

**Comment by morgante** [comment]
Theoretically it could, but I'm not sure it's a big enough improvement to justify breaking the current interface.

**Comment by zolech** [comment]
Ok, I suppose switching to **iam** storage_bucket submodule would be less time consuming.
