### ISSUE TITLE
Support for new Lifecycle conditions: MatchesPrefix, MatchesSuffix

### ISSUE THREAD

**Issue by domZippilli** [terraform-google-modules/terraform-google-cloud-storage#180]
### TL;DR

GCS has added new lifecycle conditions for object name prefixes and suffixes:
https://cloud.google.com/storage/docs/lifecycle#conditions

Requesting addition of this as a nested condition ([ref](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#nested_condition)).

**Comment by elops-od** [comment]
hi
any updates ?
