### ISSUE TITLE
Include a matches_prefix variable in this module

### ISSUE THREAD

**Issue by raylaijh** [terraform-google-modules/terraform-google-cloud-storage#224]
### TL;DR

Normal GCS bucket storage provider allows the configuration of [matches_prefix](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#matches_prefix), but this module doesn't have that option. 

Looking to see if its possible to include that variable as part of this module

### Terraform Resources

```markdown
google_storage_bucket
```

**Comment by Ameausoone** [comment]
It's available since here https://github.com/terraform-google-modules/terraform-google-cloud-storage/commit/8db2eb352c3998b4981553e2bdeb72c2c7c34f5b#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR124 

But there were no new release since this commit.
