### ISSUE TITLE
Error: An argument named "bucket_policy_only" is not expected here

### ISSUE THREAD

**Issue by elainedavid** [terraform-google-modules/terraform-google-cloud-storage#25]
Hi,

I'm using the module and started running into this issue today.  I have no explicit reference to this input variable.  My TF template is below:

module "search_cloud_storage" {
  source  = "terraform-google-modules/cloud-storage/google"
  version = "1.1.0"

  project_id    = var.our_project
  prefix        = "mstr"
  names         = ["gcts", "df"]
  labels        = {
        name = "our label here"
  }
  storage_class = "STANDARD"
  location      = var.region
}

Error when running "terraform validate" or "terraform plan", for both versions 1.0.0 and 1.1.0:

Error: Unsupported argument

  on .terraform/modules/search_cloud_storage/terraform-google-modules-terraform-google-cloud-storage-c011106/main.tf line 33, in resource "google_storage_bucket" "buckets":
  33:   bucket_policy_only = lookup(

An argument named "bucket_policy_only" is not expected here.

**Comment by morgante** [comment]
Please include your Terraform provider versions. `terraform version` and `terraform providers`.

**Comment by elainedavid** [comment]
USSFOMLP1VHFD59:Terraform eladavid$ terraform providers
.
├── provider.google
├── provider.google.impersonated
├── module.gcp_vault
│   ├── provider.external
│   ├── provider.google ~> 2.0
│   ├── provider.google.impersonated (from state)
│   ├── provider.local
│   ├── provider.template
│   └── provider.tls
├── module.jobs_publisher_service_account
│   ├── provider.google (inherited)
│   ├── provider.google.impersonated (from state)
│   └── provider.template
├── module.jobs_pubsub
│   └── provider.google (inherited)
├── module.jobs_pubsub_test
│   └── provider.google (inherited)
├── module.jobs_subscriber_service_account
│   ├── provider.google (inherited)
│   ├── provider.google.impersonated (from state)
│   └── provider.template
├── module.load-balancer-search
│   ├── provider.google ~> 2.7.0
│   ├── provider.google-beta ~> 2.7.0
│   ├── provider.tls
│   └── module.lb
│       ├── provider.google (inherited)
│       └── provider.google-beta (inherited)
├── module.search_cloud_storage
│   └── provider.google (inherited)
├── module.search_memorystore
│   └── provider.google (inherited)
├── module.search_service_account
│   ├── provider.google (inherited)
│   ├── provider.google.impersonated (from state)
│   └── provider.template
└── module.search_vm_instance_template
    └── provider.google (inherited)


Terraform v0.12.10
+ provider.external v1.2.0
+ provider.google v2.7.0
+ provider.google-beta v2.7.0
+ provider.local v1.4.0
+ provider.template v2.1.2
+ provider.tls v2.1.1

**Comment by morgante** [comment]
You need to upgrade your Google provider to at least v2.9.0 to use this module: https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGELOG.md#290-june-19-2019
