### ISSUE TITLE
Dependency requirement conflict when using this module along GKE module

### ISSUE THREAD

**Issue by dvega-flexion** [terraform-google-modules/terraform-google-cloud-storage#274]
### TL;DR

See versions.tf in GKE module: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/gke-cluster-standard/versions.tf

The error happens when updating the later package, which we need

```
Error: Failed to query available provider packages

│ 

│ Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the given constraints >= 3.4.0, >= 3.53.0, >= 4.47.0, != 4.49.0, != 4.50.0, >= 4.55.0, >= 5.0.0, <

│ 5.0.0
```

### Expected behavior

Module is compatible with google & google/beta >= 5.0.0

### Observed behavior

It is not

### Terraform Configuration

```hcl
N/A
```

### Terraform Version

```sh
1.5.5
```

**Comment by aryasoni98** [comment]
I would like to work on it

**Comment by pielat** [comment]
@aryasoni98 is it still in progress? It's still failing for me when I want to upgrade my providers to version >= 5.0.0
