### ISSUE TITLE
Access control Fine-grained and Uniform

### ISSUE THREAD

**Issue by Vendin** [terraform-google-modules/terraform-google-cloud-storage#29]
How set `Access control` setting on `Fine-grained` in bucket through the terraform module ? 

![image](https://user-images.githubusercontent.com/9011975/70752942-bcc17c80-1d44-11ea-9ff5-ba510f20c3fc.png)

**Comment by morgante** [comment]
You can set `bucket_policy_only` to false:

```
....
bucket_policy_only = {my-bucket-name = false}
....
```

**Comment by Gatsby-Lee** [comment]
@morgante Thank you
