### ISSUE TITLE
automatic bucket label not sanitized properly

### ISSUE THREAD

**Issue by pmarschik** [terraform-google-modules/terraform-google-cloud-storage#30]
3e7b6004d8c962546939d803fab07310a2c22e94 introduced setting the prefix + name as a bucket label.

However the sanitizing of the name is not complete:

 * https://cloud.google.com/storage/docs/key-terms#bucket-labels states:
   > [...] Keys and values can only contain lowercase letters, numeric characters, underscores, and dashes. International characters are allowed. [...]
 * However https://cloud.google.com/storage/docs/key-terms#bucket-names states:
    > Also, bucket names can be used with a CNAME redirect, which means they need to conform to DNS naming conventions
 * all the sanitization that happens is a `lower(...)` but it does not remove `.` and also doesn't handle the case where the name would be longer than 63 characters etc.

In our case we use a valid DNS name as a bucket name (e.g. `host-name.example.com`).
This module would then add the label `name = host-name.example.com` which violates the bucket label constraints.

Steps to reproduce:

```tf
module "gcs_terraform_state" {
  source            = "terraform-google-modules/cloud-storage/google"
  version           = "~> 1.0"
  ...
  names             = ["host-name.example.com"]
  ...
}
```

```bash
terraform apply -auto-approve
```

Result:
```
[...]
Error: googleapi: Error 400: Invalid argument, invalid

  on .terraform/modules/gcs_terraform_state/terraform-google-modules-terraform-google-cloud-storage-231f6ed/main.tf line 21, in resource "google_storage_bucket" "buckets":
  21: resource "google_storage_bucket" "buckets" {
```

Expected Result:

```
[...]
Apply complete! Resources: X added, Y changed, Z destroyed.
```

Solutions:

 * either properly sanitize the auto-generated label
 * or give an option to disable automatically setting the label

**Comment by aaron-lane** [comment]
Looks like this may have been fixed by https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/31.

**Comment by bharathkkb** [comment]
Yup looks like it should now change `.` to `-`
