### ISSUE TITLE
Need to upgrade terraform-google-modules/kms/google to support the provider v6

### ISSUE THREAD

**Issue by lra** [terraform-google-modules/terraform-google-cloud-storage#344]
### TL;DR

terraform-google-modules/kms/google v2 used in https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/modules/simple_bucket/main.tf#L130-L131 is still enforcing `provider[registry.terraform.io/hashicorp/google] >= 3.53.0, < 6.0.0`

It needs to be upgraded to https://github.com/terraform-google-modules/terraform-google-kms/releases/tag/v3.0.0 to support `hashicorp/google` v6

### Terraform Configuration

```hcl
module "cloudsql-backup-buckets" {
  source  = "terraform-google-modules/cloud-storage/google//modules/simple_bucket"
  version = "~> 6.1"
}
```

### Terraform Version

```sh
Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.44.0
+ provider registry.terraform.io/hashicorp/google-beta v5.44.0
```

**Comment by joemiller** [comment]
Hit this as well, preventing v6 upgrade

**Comment by kimllee** [comment]
I'm facing the same issue
https://github.com/terraform-google-modules/terraform-google-cloud-storage/issues/348#issuecomment-2399787449
