### ISSUE TITLE
Missing support for google provider v6

### ISSUE THREAD

**Issue by oralmeida** [terraform-google-modules/terraform-google-cloud-storage#348]
### TL;DR

Using this module prevents us to use https://github.com/hashicorp/terraform-provider-google/releases/tag/v6.3.0

**Comment by strangeman** [comment]
Need to update the version of the `encryption_key` module
```

module "encryption_key" {
  count              = var.encryption == null ? 0 : (var.encryption.default_kms_key_name == null ? 1 : 0)
  source             = "terraform-google-modules/kms/google"
  version            = "~> 2.0"
  project_id         = var.project_id
  location           = var.location
  keyring            = var.name
  prevent_destroy    = false
  keys               = [var.name]
  set_decrypters_for = [var.name]
  set_encrypters_for = [var.name]
  decrypters         = ["serviceAccount:${data.google_storage_project_service_account.gcs_account.email_address}"]
  encrypters         = ["serviceAccount:${data.google_storage_project_service_account.gcs_account.email_address}"]
}
```

**Comment by strangeman** [comment]
https://github.com/terraform-google-modules/terraform-google-cloud-storage/pull/343

**Comment by kimllee** [comment]
Hi,
Is it possible to merge this change into the submodules too please ?
I'm using the submodule simple_bucket and it's still linked to the the version 2.3 of the kms module so I can't use Google's v6 provider...

Thanks a lot.


`
  source = "terraform-google-modules/cloud-storage/google//modules/simple_bucket"
......
Downloading registry.terraform.io/terraform-google-modules/kms/google 2.3.0 for bucket_backup_bdd.encryption_key...`


![image](https://github.com/user-attachments/assets/f0fb6d6e-c7b4-4a90-a03f-3f8777007e32)
