### ISSUE TITLE
Feature request: Allow creation of top level folders in bucket

### ISSUE THREAD

**Issue by kenttoku** [terraform-google-modules/terraform-google-cloud-storage#46]
I would like to be able to create buckets with a few top level folders within it. 
I'm thinking of something that looks like this:

```
module "gcs_buckets" {
  source  = "terraform-google-modules/cloud-storage/google"
  version = "~> 1.3"
  project_id  = "<PROJECT ID>"
  names = ["first", "second"]
  folders = {
    first = ["test", "dev", "prod"]
  }
}
```

which would result in the "first" bucket that contains 3 folders (test, dev, prod), while the second bucket would be empty. 

Thank you,
Kent

**Comment by morgante** [comment]
This seems like a reasonable addition and could be implemented using the [storage_object](https://www.terraform.io/docs/providers/google/r/storage_bucket_object.html) resource.

Happy to accept a PR.
