### ISSUE TITLE
lifecycle_rules not working for action.type=delete

### ISSUE THREAD

**Issue by christopher-tin** [terraform-google-modules/terraform-google-cloud-storage#51]
_There are two issues but they are both closely related_

**Steps to repeat issue**
Add the following block for the module:
``` 
lifecycle_rules = [{
    action = {
      type = "Delete"
    }
    condition = {
      age = 1
    }
  }]
```

Error occurs when planning or applying:
```  Error: Invalid value for module argument
  on .terraform/somepathhere/main.tf line 42, in module "my-bucket":
  42:   lifecycle_rules = [{
  43:     action = {
  44:       type = "Delete"
  46:     }
  47:     condition = {
  48:       age = 1
  49:     }
  50:   }]
The given value is not suitable for child module variable "lifecycle_rules"
defined at
.terraform/modules/somepathhere/terraform-google-cloud-storage-1.5.0/variables.tf:130,1-27:
element 0: attribute "action": attribute "storage_class" is required.
```

When I apply the required storage_class to the module:
```
lifecycle_rules = [{
    action = {
      type = "Delete"
      storage_class = "STANDARD"
    }
    condition = {
      age = 1
    }
  }]
```

`terraform plan` will work,  but on a `terraform apply` we get another error:
```
Error: googleapi: Error 400: Invalid argument, invalid
  on .terraform/modules/somepathhere/main.tf line 21, in resource "google_storage_bucket" "buckets":
  21: resource "google_storage_bucket" "buckets" {
```

**Workaround**
I modified the local copy of the module to ignore the storage_class and I was able to run both a `plan` and `apply` with no issues.

**Comment by morgante** [comment]
Can you try this config?

```
lifecycle_rules = [{
    action = {
      type = "Delete"
      storage_class = null
    }
    condition = {
      age = 1
    }
  }]
```

**Comment by christopher-tin** [comment]
Hey @morgante, that works and I'm able to apply without modifying the module. Maybe all that needs to be done is to update the instructions so it's more up to date?

e.g. this example doesn't actually work: https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/examples/simple_bucket/main.tf

**Comment by morgante** [comment]
Yeah we should update the example and make sure the examples are included in tests. @umairidris could you take a look?

**Comment by umairidris** [comment]
It looks like you're using the example for the simple_bucket submodule for the main module.

I can send a PR to allow omitting this field in the main module.

@morgante I realized the samples are a bit confusing (https://github.com/terraform-google-modules/terraform-google-cloud-storage/tree/master/examples) with simple_bucke vs multiple_buckets.

Should I rename them to simple_bucket_module and main_module?

**Comment by morgante** [comment]
Honestly I think we might want to remove the `simple_bucket` example entirely or update it to use the main module.
