### ISSUE TITLE
Feature: Need to Dynamically assign encryption

### ISSUE THREAD

**Issue by mike-19** [terraform-google-modules/terraform-google-cloud-storage#55]
for multi-regional buckets with encryption, the encryption key from the global key-ring will not work, The keys need to be bound  to the regional resource itself 
eg: Bucket in US can't have the global key to encrypt, it should have a key from US location to encrypt

**Comment by morgante** [comment]
Is the `encryption_key_names` feature insufficient to handle this?

**Comment by mike-19** [comment]
@morgant yes the variable definition is well sufficient however that's user passed or user-defined, We have a KMS and a suite of IAM  roles created along with one terraform code, I am stuck at putting logic on how to different assign the KMS key according to bucket location dynamically instead user provided 

Do you have a sample `tfvars` for the code in `main.tf` I am looking for how the values of the variables defined especially for `encryption_key_names` since  I don't see a `selflink` constructed while the value should be of format, it may report bad crypto key format

**Comment by morgante** [comment]
You should be invoking the module something like one of the examples here: https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/examples/simple_bucket/main.tf

**Comment by mike-19** [comment]
thx @morgante  i am still trying to understand the `encryption_key_names` are you taking the selflink as user input or just the cryptokey name . The documentation is little confusing thats the very specific reason i asked for the values that is being passed . I dont see you construct the selflink in the main.tf

**Comment by morgante** [comment]
I believe providing a selflink for `encryption_key_names` should work.

**Comment by mike-19** [comment]
@morgante  let me try that and keep you posted

**Comment by jasonthemartyr** [comment]
I wasn't able to get this to work with self_link or the name of the key. it seems to always default to google managed key. The readme could use an example of how this is suppose to be formatted.

**Comment by jasonthemartyr** [comment]
ah here we go I had to do this:
```bash
  encryption_key_names = { "first" = "${data.google_kms_crypto_key.my_crypto_key.self_link}" }

```

`first` is the bucket suffix declared in `names`. its in this [line](https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/f2f3d3c4699bac795c9ed9bbc110ec1b27db8486/main.tf#L57).
