### ISSUE TITLE
Migrate to Terraform 0.12

### ISSUE THREAD

**Issue by Dev25** [terraform-google-modules/terraform-google-cloud-storage#7]
As other modules under `github.com/terraform-google-modules` are moving to TF v0.12 in recent weeks, this one should too.

I'm happy to help out with this one if required.

**Comment by morgante** [comment]
@Dev25 It's on our backlog but we won't get to it for another week or two so if you have bandwidth before then we'd be happy to look at a pull request.

**Comment by Dev25** [comment]
No problem, i'll send over a PR for this one (and possibly some other modules) early next week @morgante

**Comment by morgante** [comment]
Thanks!

**Comment by aaron-lane** [comment]
Fixed by #9.
