### ISSUE TITLE
How-To Simple Bucket Module

### ISSUE THREAD

**Issue by darkn3rd** [terraform-google-modules/terraform-google-cloud-storage#78]
The link referenced in the published content gets 404 error:

* https://registry.terraform.io/modules/terraform-google-modules/cloud-storage/google/

I looked through the [docs](https://www.terraform.io/docs/modules/sources.html#generic-git-repository) and I cannot discern how to reference this path in source.

How can we use the simple_module short of copy the directory locally.

**Comment by bharathkkb** [comment]
Hi @darkn3rd 
You can reference it like this 
```hcl
module "bucket" {
  source  = "terraform-google-modules/cloud-storage/google//modules/simple_bucket"
  version = "~> 1.3"
.
.
}

```
Docs with sample usage [here](https://github.com/terraform-google-modules/terraform-google-cloud-storage/tree/master/modules/simple_bucket#usage).
Feel free to re open if needed.

**Comment by darkn3rd** [comment]
@bharathkkb 
I think initially I couldn't find this as I was using docs from the Terraform registry, which has broken links.
* https://registry.terraform.io/modules/terraform-google-modules/cloud-storage/google/modules/simple_bucket

The GitHub docs work.

I eventually found TF docs to do this by `"git::https://github.com/terraform-google-modules/terraform-google-cloud-storage.git//modules/simple_bucket?ref=v1.7.0"`
