### ISSUE TITLE
Terraform Google Provider 3.41.0 Breaking Change for `is_live`

### ISSUE THREAD

**Issue by heiny** [terraform-google-modules/terraform-google-cloud-storage#89]
Hello,

Looks like the google terraform provider version 3.41.0 removed support for is_live:
https://github.com/hashicorp/terraform-provider-google/commit/d1014fe3b47d377db9a6eee9cfa9cbb0412c18e2#

We'll patch our local copy of the module but can you create an official release to remove this?
https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/master/main.tf#L102

Too bad terraform didn't provide the warning, looks like it was marked as "Removed" since July 2019.

Thanks

**Comment by morgante** [comment]
Thanks, looks like we need to replace it with `with_state`: https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#is_live-is-now-removed

A PR would be appreciate if someone gets a chance.

**Comment by jaketf** [comment]
on it.

**Comment by heiny** [comment]
Are you thinking you want to make the module backward compatible by applying `with_state=LIVE` when `is_live` is specified?

**Comment by morgante** [comment]
Yes, backwards compatibility would be preferred.

**Comment by jaketf** [comment]
My thought was for with_state to take precedence over but fall back to is_live take a peak at #90 if this looks like what you'd expect.

**Comment by heiny** [comment]
Thanks for picking this up @jaketf 
@morgante Considering this is a breaking change, is the plan to create a new release build once this is finalized?  Trying to determine a time frame for us to pick up the new module build.  Thank you

**Comment by morgante** [comment]
Yeah we can do a patch release once this is merged.

**Comment by heiny** [comment]
Fixed both modules in my PR. Didn't realize you can do all of this via the web UI, very handy.

**Comment by heiny** [comment]
@morgante

**Comment by MartinPetkov** [comment]
Hi, could we get an idea of when the next release will be made? Our tests are currently failing due to this issue.

**Comment by morgante** [comment]
> Hi, could we get an idea of when the next release will be made? Our tests are currently failing due to this issue.

I highly recommend you pin your provider version as we don't promise immediate compatibility with new provider versions.

**Comment by tenevdev** [comment]
> > Hi, could we get an idea of when the next release will be made? Our tests are currently failing due to this issue.
> 
> I highly recommend you pin your provider version as we don't promise immediate compatibility with new provider versions.

@morgante, I'm very new to terraform but just from reading https://www.terraform.io/docs/configuration/provider-requirements.html#requiring-providers doesn't this say that the best practice is for the module author to declare a version constraint which specifies which provider versions the module is compatible with?
