### ISSUE TITLE
1.7.1 is borked

### ISSUE THREAD

**Issue by WillBeebe** [terraform-google-modules/terraform-google-cloud-storage#93]
This change fixes it [link](https://github.com/terraform-google-modules/terraform-google-cloud-storage/commit/f73041b904d8f5c7020efb84737d54869e394738)

Can we cut a patch release?

Here's the error you get w/ `1.7.1`

```
Error: Unsupported argument

  on .terraform/modules/gcs_buckets/main.tf line 98, in resource "google_storage_bucket" "buckets":
  98:         is_live               = lookup(lifecycle_rule.value.condition, "is_live", null)

An argument named "is_live" is not expected here.
```

**Comment by morgante** [comment]
I can release a patch but you should also strongly consider pinning your provider version.

**Comment by WillBeebe** [comment]
Will do, thanks Morgante
