### ISSUE TITLE
terraform 0.13 now supports for_each on modules: what does it mean for the future of this one? 

### ISSUE THREAD

**Issue by adrian-gierakowski** [terraform-google-modules/terraform-google-cloud-storage#96]
Should a new module, which creates a single bucket with associated iam bindings and folders, be created and this module be implemented in terms of this new module? 

Or maybe it doesn't even make sense to have a module which creates multiple buckets anymore? It seems to me that the pattern used in this module (and many other terraform-google-modules), namely creating multiple similar groups of resources using for_each on each of them, was simply a workaround used due to lack of support for for_each on user defined modules. 

There is still a value in grouping resources which ofter go together (like bucket + iam + folders in that bucket), but having a module create multiple such groups seems redundant in 0.13.

**Comment by morgante** [comment]
The root module could probably be updated to wrap the [simple bucket](https://github.com/terraform-google-modules/terraform-google-cloud-storage/tree/master/modules/simple_bucket).
