### ISSUE TITLE
Error: Variables not allowed

### ISSUE THREAD

**Issue by markawad** [terraform-google-modules/terraform-google-cloud-storage#97]
Hello, 

I am trying to use a remote state file in gcs and passing the credentials to this backend through hashicorp vault. Is this even possible? Passing the credentials to the provider works, but not gcs.

### main.tf
```
data "vault_generic_secret" "gcp_credentials" {
  path = "<<path_is_added_here>>"
}

// Configure the Google Cloud provider
provider "google" {
  credentials = data.vault_generic_secret.gcp_credentials.data_json
  project     = var.gcp_project
  region      = "europe-west3"
}
```

### state.tf
```
terraform {
  backend "gcs" {
    bucket  =  "<<bucket_added>>"
    prefix  = "<<prefix_added>>"
    credentials = data.vault_generic_secret.gcp_credentials.data_json // here is my problem
}
```

I have tried adding it as a local as well and I still get this error. Any help is appreciated.

**Comment by morgante** [comment]
Variables are not possible in state config. This is a Terraform restriction not specific to GCS.
